### ISSUE TITLE
Race/class location in statblock

### ISSUE THREAD

**Issue by Kurohyou** [mjcadz/sfrpgtools#4]
The starfinder statblock format has a creature's race/class as a separate line between XP and the alignment/size/type/subtype.

Not a truly big deal, but I'm working on getting statblock import functionality into the [Starfinder HUD Roll20 character sheet](https://app.roll20.net/forum/post/5145005/starfinder-alpha-wip-discussion-thread/?pageforid=5527476). Having the statblock output from your awesome tool match the official format would make it much easier to parse correctly.

EDIT: Similarly, Resolve Points should be next to the creatures HP.

**Comment by dicedatalore** [comment]
fixed. will go out with the next site update.
