### ISSUE TITLE
Ship builder

### ISSUE THREAD

**Issue by dicedatalore** [mjcadz/sfrpgtools#5]
along similar lines as the monster builder

**Comment by styler3** [comment]
Am working on this now.

**Comment by dicedatalore** [comment]
@styler3 awesome!

I already did the data https://gist.github.com/mjcadz/5fb7e7b01f9283d1a8503ad403840389

and one of the design goals I had was to do a seperate random ship generator that has minimal inputs like size and purpose(exploration,racing,warship) maybe it would be possible to use the same generation code?

**Comment by styler3** [comment]
This data is awesome. I'm glad I didn't get too far into entering it myself.

**Comment by dicedatalore** [comment]
@styler3 do you mind if I take this over? I'd like to get it out with the next update

**Comment by styler3** [comment]
@mjcadz By all means. All I have done so far is transform the data (you can find it in my fork's ship builder branch). The plan was to give everything a cost and a value (in SBP, power consumption, etc.) then you can just create a single function for adding any type of component to the ship. Feel free to use it if you like, or just do it your own way :smile:
